import type { Metadata } from "next";

import ReactQueryProvider from "@/components/providers/react-query-provider";
import ToastProvider from "@/components/providers/toast-provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Mcwale",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className=" scroll-smooth">
      <body>
        <ReactQueryProvider>
          <ToastProvider />
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
