import Footer from "@/components/layouts/Footer";
import Navbar from "@/components/layouts/Navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Mcwale",
  description: "Generated by create next app",
};

export default function SiteLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className=" scroll-smooth">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
